fix: typo in my last name in Sign-offs
stacksgov/sips pull request #126
Opened 2023-04-19 18:33 UTC by obycode

Looks like someone mistyped my last name and it didn't get caught. I
also fixed the formatting of this list to look nicer and added an email
address for MattyTokenomics for consistency.

2023-04-20 23:01 UTC, whoabuddy requested changes

2023-04-20 23:41 UTC, obycode commented on sips/sip-015/sip-015-network-upgrade.md
> +Sign-off: Brice Dobry <brice@hiro.so>, Jason Shrader <jason@joinfreedhold.com>,
Ah I missed that! Is there a typo in your email too? "freedhold"

2023-04-21 03:43 UTC, jcnelson commented
We good on this? Can I merge?

2023-04-21 14:13 UTC, whoabuddy commented on sips/sip-015/sip-015-network-upgrade.md
> +Sign-off: Brice Dobry <brice@hiro.so>, Jason Shrader <jason@joinfreedhold.com>,
Ah good catch, I didn't see that - it should be `jason@joinfreehold.com`

2023-04-21 14:14 UTC, whoabuddy approved these changes

2023-04-21 14:17 UTC, merged